export const ACCESS_TOKEN = "access_token";
export const EXPIRED_TIME = "expired_time";
export const COOKIE_EXPIRED_DATE = 7;

export const NOT_HAVE_VALUE_LABEL = "- -";
export const NOT_AVAILABLE_VALUE = "N/A";

export const DEBOUNCE_TIME_IN_MILLISECOND = 500;

export const DEFAULT_ALL_VALUE = -999;

export const PAGE_SIZE_OPTIONS = [50, 100, 150, 200];
export const DEFAULT_PAGINATION_SKIP_TAKE = {
  skip: 0,
  take: PAGE_SIZE_OPTIONS[0],
};

export const APP_PROGRESS_ID = "app-progress";

// Date, Time Format
export const YEAR_FORMAT = "YYYY";
export const DATE_FORMAT = "DD/MM/YYYY";
export const DATE_TIME_FORMAT = "DD/MM/YYYY HH:mm";
export const TIME_FORMAT = "HH:mm";

export const APP_TITLE = "Nextjs 14";
export const APP_DESCRIPTION = "Generated by create next app";
